### ISSUE TITLE
next/vite branch: invalid JS syntax when using slashes inside backticks 

### ISSUE THREAD

**Issue by macCesar** [tidev/liveview#217]
I'm getting `invalid JS syntax` with code like this:

```javascript
code += `\n</Alloy>`
```

If I change the backticks ( ` ) to single/double quotes OR remove the slash ( / ).. the error goes away!
```javascript
// NO syntax error
code += '\n</Alloy>'
code += "\n</Alloy>"

code += `\n<Alloy>` <-- slash removed ( not an option because it is need it )
```

Of course I can change it to use single/double quotes, but what about when using backticks, variables and closing tags?
```javascript
code += `\n${spacing}</${element}>`
```

**Comment by janvennemann** [comment]
That's actually one of the issues i'm working on right now with the upgrade to Vite 4. There is a custom Vite plugin that will scan source code for dynamic requires and it can't handle a few things properly, like template literals.

**Comment by janvennemann** [comment]
This should now be fixed in the latest alpha release.
