### ISSUE TITLE
missing TSS file generates warning; doesn't load app properly

### ISSUE THREAD

**Issue by jasonkneen** [tidev/liveview#222]
I have an app with a login screen that doesn't have a TSS file. When loading liveview complains about no `login.tss` file and appears to ignore the warning but then app functionality doesn't work and fires errors below

Adding an empty tss fixed it.

```[INFO]  [vite] connected.
15:47:37 [vite] Internal server error: Failed to resolve import "/Users/jkneen/Documents/Appcelerator_Studio_Workspace/theWasteConnect/waste_connect_app/app/styles/screens/login.tss" from "app/controllers/screens/login.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/jkneen/Documents/Appcelerator_Studio_Workspace/theWasteConnect/waste_connect_app/app/controllers/screens/login.js:1:1
  1  |  var Alloy = require('/@fs/Users/jkneen/.nvm/versions/node/v16.14.0/lib/node_modules/alloy/Alloy/template/lib/alloy.js?v=9dc858bc'),
     |  ^
  2  |    Backbone = Alloy.Backbone,
  3  |    _ = Alloy._;```

**Comment by janvennemann** [comment]
Thanks Jason for reporting this. This is currently a known issue with the latest alpha release. Views that don't have a controller file also don't work. I'll look into this for the next update.

**Comment by janvennemann** [comment]
@jasonkneen Give the latest 2.0.0-alpha.10 a try, this should be fixed now.
