### ISSUE TITLE
 Package "@esbuild/darwin-arm64" could not be found

### ISSUE THREAD

**Issue by jonasfunk** [tidev/liveview#225]
Was previously running node 14, but after reading on Slack, that you should use node 16 or 18 with liveview, I upgraded to node 16. 
The project is a Typescript project, and after I run ti serve ios I get this error. 

```
[vite] Internal server error: The package "@esbuild/darwin-arm64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
```

Installing @esbuild/darwin-arm64 does not help. Using an M1 Macbook. Same happens with node 18.

**Comment by jonasfunk** [comment]
Found out that I should install @esbuild/darwin-arm64@0.18.20 globally, and then it would run

**Comment by janvennemann** [comment]
This means that something you use actually imports this package. Probably behind a condition or something. Do you use any node packages in your app?

**Comment by jonasfunk** [comment]
I thought it was because Vite uses esbuild. We use these modules:

```
    "blurhash": "^1.1.3",
    "fuse.js": "^6.4.6",
    "fuzzysort": "^1.1.4",
    "gsap": "^3.6.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "npm-remote-ls": "^1.3.2",
    "queue-promise": "^2.2.1",
    "semver": "^7.3.2",
    "stream-http": "^3.1.1",
    "tslib": "^2.0.3",
```

**Comment by janvennemann** [comment]
Have you tried re-installing liveview after changing node version? Maybe some packages that were not installed initially while you were still running Node 14 is messing something up now.

**Comment by jonasfunk** [comment]
I think it was because liveview wasn't installed globally. I doesn't complain about esbuild after liveview is installed globally.

**Comment by janvennemann** [comment]
Okay great, then sounds like this is solved now. It's actually another issue that liveview is installed globally right now because that can cause trouble when running it in multiple projects at the same time, so this may change in the future.
